### ISSUE TITLE
[Bug]  No module named 'mmcv._ext

### ISSUE THREAD

**Issue by odark00** [VBTI-development/onedl-mmrotate#7]
### Prerequisite

- [x] I have searched [Issues](https://github.com/vbti-development/onedl-mmrotate/issues) and [Discussions](https://github.com/vbti-development/onedl-mmrotate/discussions) but cannot get the expected help.
- [x] I have read the [FAQ documentation](https://onedl-mmrotate.readthedocs.io/en/latest/notes/4_faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version (master)](https://github.com/vbti-development/onedl-mmrotate) or [latest version (1.x)](https://github.com/vbti-development/onedl-mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/vbti-development/onedl-mmrotate

### Environment

I am trying to setup onedl-mmrotate with python3.13 and pytorch 2.9 , and this issue appears

### Reproduces the problem - code sample

 python demo/image_demo.py demo/demo.jpg configs/oriented-rcnn-le90_r50_fpn_1x_dota.py models/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg

ModuleNotFoundError: No module named 'mmcv._ext'

### Reproduces the problem - command or script

 python demo/image_demo.py demo/demo.jpg configs/oriented-rcnn-le90_r50_fpn_1x_dota.py models/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg

### Reproduces the problem - error message

python demo/image_demo.py demo/demo.jpg configs/oriented-rcnn-le90_r50_fpn_1x_dota.py models/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg
Could not import OneDL
Traceback (most recent call last):
  File "/workspaces/envinroment_obb_training/onedl-mmrotate/demo/image_demo.py", line 4, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/usr/local/lib/python3.13/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/usr/local/lib/python3.13/site-packages/mmdet/apis/det_inferencer.py", line 22, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/usr/local/lib/python3.13/site-packages/mmdet/evaluation/__init__.py", line 4, in <module>
    from .metrics import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/mmdet/evaluation/metrics/__init__.py", line 5, in <module>
    from .coco_metric import CocoMetric
  File "/usr/local/lib/python3.13/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval, COCOevalMP
  File "/usr/local/lib/python3.13/site-packages/mmdet/datasets/__init__.py", line 43, in <module>
    from .utils import get_loading_pipeline
  File "/usr/local/lib/python3.13/site-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/usr/local/lib/python3.13/site-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
                             PackTrackInputs, ToTensor, Transpose)
  File "/usr/local/lib/python3.13/site-packages/mmdet/datasets/transforms/formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/usr/local/lib/python3.13/site-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/usr/local/lib/python3.13/site-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/usr/local/lib/python3.13/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
                             bitmap_to_polygon, polygon_to_bitmap)
  File "/usr/local/lib/python3.13/site-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/usr/local/lib/python3.13/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.13/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
        '_ext',
        ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "/usr/local/lib/python3.13/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mmcv._ext'

### Additional information

_No response_

**Comment by lauriebax** [comment]
Hi, we currently don't support prebuilt wheels for onedl-mmcv for python 3.13. we have for 3.12 (see mmwheels.onedl.ai for all our published versions). So you could either downgrade your python or build onedl-mmcv from source. This should solve the _ext problem.

**Comment by odark00** [comment]
Even with python3.12 I am still encountering an issue

python demo/image_demo.py demo/demo.jpg /workspaces/envinroment_obb_training/onedl-mmrotate/configs/oriented_rcnn/oriented-rcnn-le90_r50_fpn_1x_dota.py models/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg
Could not import OneDL
Traceback (most recent call last):
  File "/workspaces/envinroment_obb_training/onedl-mmrotate/demo/image_demo.py", line 4, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/usr/local/lib/python3.12/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/usr/local/lib/python3.12/site-packages/mmdet/apis/det_inferencer.py", line 22, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/usr/local/lib/python3.12/site-packages/mmdet/evaluation/__init__.py", line 4, in <module>
    from .metrics import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mmdet/evaluation/metrics/__init__.py", line 5, in <module>
    from .coco_metric import CocoMetric
  File "/usr/local/lib/python3.12/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval, COCOevalMP
  File "/usr/local/lib/python3.12/site-packages/mmdet/datasets/__init__.py", line 43, in <module>
    from .utils import get_loading_pipeline
  File "/usr/local/lib/python3.12/site-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/usr/local/lib/python3.12/site-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "/usr/local/lib/python3.12/site-packages/mmdet/datasets/transforms/formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/usr/local/lib/python3.12/site-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/usr/local/lib/python3.12/site-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/usr/local/lib/python3.12/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/usr/local/lib/python3.12/site-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/usr/local/lib/python3.12/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.12/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by lauriebax** [comment]
Hi, to figure this out you need:
- your installed torch version, including cuda version (e.g. 2.9.0+cu129)
- the output of `mim install -v onedl-mmcv --only-binary=onedl-mmcv`
Your torch+cuda+python version should be present under the right folder at https://mmwheels.onedl.ai/. The install command should also point to the right url including the correct subfolder.
If the torch+cuda+python version you are using is not present in the index you should up/downgrade to a version that is supported. If that is not an option you have to [build onedl-mmcv from source.](https://onedl-mmcv.readthedocs.io/en/latest/get_started/build.html)

**Comment by hillsonghimire** [comment]
Hi, I am facing the same issue trying to install it in my HPC environment. Tried different versions but wasn't able to resolve it. @DrWillway  did you find any solutions?

**Comment by lauriebax** [comment]
@hillsonghimire  I have updated the [FAQ](https://onedl-mmcv.readthedocs.io/en/latest/faq.html) with a couple of steps that could also help find out why it won't work. You say you are installing it on a HPC environment, maybe the manylinux version is not the same as the prebuilt wheels (see step 3.3). In that case you need to build it from source.
